### ISSUE TITLE
1.7.0 AOT compilation error with 0.4.3 (not on 1.7.0-alpha2!)

### ISSUE THREAD

**Issue by sritchie** [Prismatic/schema#236]
Hey guys,

I was hoping that 0.4.3 had fixed this issue, but I'm still seeing 
```
Caused by: java.lang.ClassCastException: schema.utils.SimpleVCell cannot be cast to schema.utils.PSimpleCell
```

on AOT compilation of my uberjar. The exception showed up on a function with an enum schema applied to the input; if I remove that schema, it just pops up on another function in that file (still the first time s/defn gets called in the file). Lots of other files using `schema.core/defn` compile just fine before it.

I know this has to do with a redefinition of some record or deftype, just not sure why it only shows up now. Everything works fine on 1.7.0-alpha2.

Have you guys seen this one?

**Comment by w01fe** [comment]
Well, this at least seems like a different issue than the one fixed in
0.4.3 :/.

Haven't seen this specifically, but have seen something similar before when
using AOT compilation with hadoop (under 1.6).  In that case, after digging
in it seemed like a classloader issue -- translating to this situation,
somehow there may be two versions of SimpleVCell floating around with
different classloaders (perhaps due to both source-based and AOT versions
of classes existing), and there is nondeterminism in which one gets chosen
for a particular reference.     However, I was not able to figure out how
to work around it in my case:

https://groups.google.com/forum/?fromgroups#!searchin/clojure/classloader$20aot/clojure/bqGU3VRNFhY/I1OIMeFSvX8J

I guess there could be something weird we're doing with how we package
Schema or something that could lead to this, but I don't know what it could
be.  I have seen a number of other posts about classloader issues and AOT
compilation (including w.r.t. changes in 1.7.0) on the Clojure mailing
list, so maybe someone there can shed some light on it.  Let us know if we
can do anything to help.

One thing I notice is that here:
https://github.com/Prismatic/schema/blob/master/src/clj/schema/macros.clj#L267
we type hint on the interface rather than the concrete type -- that should
be fine, but possibly changing it to the concrete type would somehow
prevent this?

**Comment by sritchie** [comment]
I went ahead and replaced it, and now I'm seeing

```
Caused by: java.lang.ClassCastException: schema.utils.SimpleVCell cannot be cast to schema.utils.SimpleVCell
```

Which is troubling :) It's definitely something with double classfile loading. Not sure how to proceed.

**Comment by w01fe** [comment]
Yeah, that's no fun :/.  Might be worth a post on the main list to see if anyone has suggestions.

**Comment by rwilson** [comment]
This may be unrelated, but I'm trying to work past the following error, which I get when on AOT compilation in my uberjar profile:

> java.lang.ClassNotFoundException: schema.utils.NamedError

Which perplexingly, is in a file that specifically imports `NamedError` so I can provide a custom JSON encoder for cheshire.
```clojure
(:import [schema.utils NamedError])
```

It compiles just fine when required in a repl and run locally (either from within a repl or with `lein run`).

**Comment by estsauver** [comment]
I just wanted to confirm that I'm still seeing this also.

**Comment by w01fe** [comment]
I'm unfamiliar with AOT, but if one of you can provide a reduced test project (or better yet, set up a test configuration for schema that illustrates the failure) we'll see what we can do to help.  Sorry for the trouble.

**Comment by madvas** [comment]
I'm also seeing this error when I want to deploy on heroku. When I compile uberjar on my machine it works ok. What's funny, in cca 1/5 deployments to heroku it's magically doesn't throw error.
```
java.lang.ClassCastException: schema.utils.SimpleVCell cannot be cast to schema.utils.PSimpleCell
```
I'm using 
```
[org.clojure/clojure "1.8.0-alpha5"]  
[prismatic/schema "1.0.1"]
```
I've used clojure 1.7.0 also, doesn't work.

**Comment by w01fe** [comment]
Thanks for the details.  I've also seen this when deploying on EMR, and
believe it to be a classloader issue, but have no idea how to handle it
--besides just turning validation off entirely by ensuring the first
Clojure commands executed by the job are:

(require '[schema.macros])
(reset! schema.macros/*compile-fn-validation* false)

which is obviously far from ideal.

**Comment by pitluga** [comment]
I ran into this as well when doing AOT compiling. If you remove the type hint here[1] the exception goes away.

[1] https://github.com/Prismatic/schema/blob/master/src/cljx/schema/utils.cljx#L184

**Comment by w01fe** [comment]
Thanks a ton for the tip -- this has been a thorn in our side forever!  Can you please try out #312 and confirm it works?  (Same goes to anyone else who cares about AOT).  Happy to cut a snapshot release if that helps, just let me know.  Thanks again!

**Comment by pitluga** [comment]
That seems to fix the issue for me.

**Comment by sritchie** [comment]
Removing the type hint worked for us as well.

**Comment by w01fe** [comment]
Just released 1.0.4 -- hope this fixes it!  Please reopen with details if you run into issues with 1.0.4.  Thanks everyone for your help with this!

**Comment by rcanepa** [comment]
Hey guys, I was trying to compile my project with lein uberjar and I stumbled upon the same error.
```
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Caused by: java.lang.ClassCastException: schema.utils.SimpleVCell cannot be cast to schema.utils.PSimpleCell
	at scv2backend.models.common$fn__4767$keyword_to_optional_keyword__4772.invoke(common.clj:23)
	at scv2backend.models.common$set_all_schema_keys_as_optional$fn__4786.invoke(common.clj:33)
```

The affected code is pretty simple and it throw the compile error when I define my keyword-to-optional-keyword function with prismatic schema like this:

````
;; This version throw a compile error
#_(s/defn keyword-to-optional-keyword :- s/Any
  [kw :- s/Keyword]
  (s/optional-key kw))

;; This version pass without erros
(defn keyword-to-optional-keyword
  [kw]
  (s/optional-key kw))

(defn set-all-schema-keys-as-optional
  [schema]
  (reduce (fn [new-schema [k v]]
            (if (instance? clojure.lang.PersistentArrayMap v)
              (assoc new-schema k (set-all-schema-keys-as-optional v))
              (if (keyword? k)
                (assoc new-schema (keyword-to-optional-keyword k) v)
                (assoc new-schema k v))))
          {}
          schema))
````

I am using the latest version of compojure-api, which uses prismatic schema 1.0.4. Any idea of what could I be doing wrong?

**Comment by w01fe** [comment]
Hmmm ... can you try `lein deps :tree` to make sure you're not getting an earlier version through some other dependency?

**Comment by atroche** [comment]
I get this error for schema 1.0.4 on Ubuntu 14.04 running Java 1.7.0_79, but not on my MacBook running 1.8.0_66. I'm running identical codebases and commands (just lein repl).

When I downgrade to 1.0.2, the error goes away on Ubuntu.

Hope this helps =)

**Comment by rcanepa** [comment]
I made sure that I wasn't getting an earlier version with `lein deps :tree` and everything was ok. I will try with version 1.0.2.

**Comment by atroche** [comment]
Oh, and I did ```lein deps :tree```, and 1.0.4 was the only version of schema.

**Comment by w01fe** [comment]
Argh, I'm sorry but I can't reproduce.  If someone can add a failing test / AOT profile that would be extremely helpful to us in fixing this and keeping it fixed.

**Comment by adwelly** [comment]
I've encountered this today, with Clojure 1.7.0 and schema 1.0.5. When schema.core is required :as s,

the function

(defn mk-row
  [v]
  {:content [v]
   :width   (count v)
   :height  1})

can be compiled with lein uberjar, but

(s/defn mk-row
  [v]
  {:content [v]
   :width   (count v)
   :height  1}) 

causes the exception, as does my original,

(s/defn mk-row :- Region
  [v :- [s/Any]]
  {:content [v]
   :width   (count v)
   :height  1})

My mk-row function is called from a number of other places some of which are schema checked and some of which are not. In and of itself, it seems perfectly straightforward.  It's probably not involved as it is used elsewhere in checked functions, but Region is defined as:

(s/defschema RegionContent [[s/Any]])

(s/defschema Region {:content RegionContent
                     :width   s/Int
                     :height  s/Int})

I admit - I'm mystified.

**Comment by w01fe** [comment]
Thanks for the report.  Are you possibly using any libraries depending on Schema that have been AOT compiled?

**Comment by adwelly** [comment]
We use the Metosin package that uses schema to document RESTful APIs with schemas. I saw from lein deps :tree that we are both using 1.0.5 but it's possible that this may be part of the issue. I'm in a position to eliminate it from this particular package so I will do so and report back here.

**Comment by ikitommi** [comment]
Hi. `lein clean` has solved some weird ClassCasts. No idea of the root cause. Also, we are not AOTing our c-apis, some discussion in here: https://github.com/metosin/compojure-api/issues/129#issuecomment-114505102
